spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 150422
    url: jdbc:mysql://localhost:3306/partner_matching_system?serverTimezone=Asia/Shanghai
  redis:
    host: 192.168.62.128
    port: 6379
    database: 0
    password: 150422
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: test # 默认加载test配置文件
  session:
    store-type: redis # redis存储session会话
logging:
  level:
    root: info
    com.neu.vansven.controller: trace #开启mybatis的sql日志输出
    com.neu.vansven.service: debug
    com.neu.vansven.mapper: debug
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  servlet:
    context-path: /vansven
  port: 8080


